# Portfolio Analysis
## Cameron Taheri

### 25 Portfolios Sorted on Book-to-Market and Investment
#### Investment = % change in total investment from t-2 to t-1

#### $\textit{Question numbers are next to each cell's title for easy reference}$

---

In [1]:
# ==============================================================================
# 0. IMPORT COMPUTATIONAL, PLOTTING, STATISTICAL PACKAGES
# ==============================================================================

# Import necessary computational and plotting packages
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import openpyxl
import tabulate

# statistical packages
import statsmodels.api as sm
from scipy.stats import f

---

In [2]:
# ==============================================================================
# 0. PORTFOLIO DATA FROM KENNETH FRENCH LIBRARY
# ==============================================================================

# pull data
path = '/Users/camerontaheri/python/emp_asset_pricing/EAP_FINAL/'
file = f"{path}FF5_VW_25BMxINV.xlsx"
df_raw = pd.read_excel(file, sheet_name="FF5_VW_25BMxINV", engine="openpyxl")

# use date as the DateTime Index and set this as the DataFrame's Index instead of its typical integer index (index label: 'date')
df_raw['Date'] = pd.to_datetime(df_raw['Date'], format='%Y%m')
df_raw.set_index('Date', inplace = True)
df_raw.index = df_raw.index + pd.offsets.MonthEnd(0)

# dataset information
print(df_raw.shape)            # returns (rows, columns)
display(df_raw.head())         # checking import is successful
display(df_raw.tail())         # checking import is successful

(748, 31)


Mkt-RF   SMB   HML   RMW   CMA    RF  LoBM LoINV  BM1 INV2  \
Date                                                                     
1963-07-31   -0.39 -0.48 -0.81  0.64 -1.15  0.27     -1.3167    0.7402   
1963-08-31    5.08 -0.80  1.70  0.40 -0.38  0.25      4.6129    5.3948   
1963-09-30   -1.57 -0.43  0.00 -0.78  0.15  0.27     -1.9646   -2.1053   
1963-10-31    2.54 -1.34 -0.04  2.79 -2.25  0.29      3.0905    1.8871   
1963-11-30   -0.86 -0.85  1.73 -0.43  2.27  0.27      3.3833   -0.0715   

            BM1 INV3  BM1 INV4  ...  BM4 INV1  BM4 INV2  BM4 INV3  BM4 INV4  \
Date                            ...                                           
1963-07-31    0.3301   -0.2615  ...   -0.9733   -1.6378   -1.3369   -1.1616   
1963-08-31    5.5023    5.3360  ...    9.8264    6.1117    4.9337   10.5004   
1963-09-30   -2.8874    0.0421  ...   -0.0418   -0.8559    0.0381    2.5793   
1963-10-31    0.9848    5.0033  ...    2.8548    3.3994    3.6042    7.0205   
1963-11-30   -0.6327   -0.8900  ...    0.1143   -3.0038   -1.6594   -2.4354   

            BM4 INV5  HiBM LoINV  BM5 INV2  BM5 INV3  BM5 INV4  HiBM HiINV  
Date                                                                        
1963-07-31    0.4111     -1.4354    0.6371   -1.6200   -1.8794      3.8378  
1963-08-31    5.0198      7.0641    4.8926    5.4709    4.9620      9.0346  
1963-09-30   -3.1633     -1.4373   -3.3967   -1.1379   -4.1796      2.1901  
1963-10-31   -2.3932      2.2689    3.0036   -1.8806   -2.7894      4.5433  
1963-11-30   -1.5999     -1.0869   -2.1569   -0.3097    4.1812     -1.6439  

[5 rows x 31 columns]

Mkt-RF   SMB   HML   RMW   CMA    RF  LoBM LoINV  BM1 INV2  \
Date                                                                     
2025-06-30    4.86 -0.02 -1.60 -3.20  1.45  0.34     12.2462    4.2310   
2025-07-31    1.98 -0.15 -1.27 -0.29 -2.07  0.34      2.9290   -0.9262   
2025-08-31    1.85  4.88  4.42 -0.68  2.07  0.38      0.6811    4.0998   
2025-09-30    3.39 -2.18 -1.05 -2.03 -2.22  0.33      5.4077    0.1741   
2025-10-31    1.95 -1.31 -3.10 -5.22 -4.03  0.37      4.2987    0.7590   

            BM1 INV3  BM1 INV4  ...  BM4 INV1  BM4 INV2  BM4 INV3  BM4 INV4  \
Date                            ...                                           
2025-06-30    0.7224    1.9224  ...    4.8098    4.4270    4.4769    6.0723   
2025-07-31   -0.8203    0.6339  ...   -0.2278    1.0260    1.0241   -0.9147   
2025-08-31    6.2112    1.2973  ...    5.4746    6.2553    6.0467    5.2336   
2025-09-30    4.9842    6.2032  ...    0.5306   -1.7599    0.9838    0.0373   
2025-10-31    2.9034   -3.4455  ...   -1.7922   -1.5637   -1.2678   -3.6354   

            BM4 INV5  HiBM LoINV  BM5 INV2  BM5 INV3  BM5 INV4  HiBM HiINV  
Date                                                                        
2025-06-30    2.3141      6.7211    6.8307    5.8811    6.4510      7.3471  
2025-07-31    0.5760      0.0873    1.4262   -3.5792   -2.0010      4.3791  
2025-08-31    4.2472      6.2049    6.6406   13.4971   12.1775      8.6698  
2025-09-30    1.1139      8.3590    1.0880   10.0741   -0.6614      2.9792  
2025-10-31   -2.0211      3.6228   -2.0149    8.1000   -4.5214     -0.9722  

[5 rows x 31 columns]

In [3]:
df_raw.index
df_raw.index.is_monotonic_increasing

True

In [4]:
# ==============================================================================
# 0. GENERATE EXCESS RETURNS
# ==============================================================================
df_25portfolio_rets = df_raw.copy()
df_25portfolio_rets = df_25portfolio_rets.iloc[:, 6:]

df_excess_rets = df_25portfolio_rets.subtract(df_raw['RF'], axis=0)

display(df_excess_rets)

LoBM LoINV  BM1 INV2  BM1 INV3  BM1 INV4  LoBM HiINV  BM2 INV1  \
Date                                                                         
1963-07-31     -1.5867    0.4702    0.0601   -0.5315      0.6810   -1.1511   
1963-08-31      4.3629    5.1448    5.2523    5.0860      6.7689    6.4693   
1963-09-30     -2.2346   -2.3753   -3.1574   -0.2279     -1.2974   -1.9629   
1963-10-31      2.8005    1.5971    0.6948    4.7133     11.5884    0.0985   
1963-11-30      3.1133   -0.3415   -0.9027   -1.1600     -5.7166   -4.0635   
...                ...       ...       ...       ...         ...       ...   
2025-06-30     11.9062    3.8910    0.3824    1.5824      5.6890    3.4806   
2025-07-31      2.5890   -1.2662   -1.1603    0.2939      5.2205    0.3379   
2025-08-31      0.3011    3.7198    5.8312    0.9173     -0.8374   -0.1766   
2025-09-30      5.0777   -0.1559    4.6542    5.8732      5.2186    1.8168   
2025-10-31      3.9287    0.3890    2.5334   -3.8155      4.9763   -2.6213   

            BM2 INV2  BM2 INV3  BM2 INV4  BM2 INV5  ...  BM4 INV1  BM4 INV2  \
Date                                                ...                       
1963-07-31   -0.6511    0.1357    0.4266   -0.7193  ...   -1.2433   -1.9078   
1963-08-31    4.1671    4.9632    3.3624    5.5228  ...    9.5764    5.8617   
1963-09-30   -0.7132   -3.4643   -0.5595   -0.7483  ...   -0.3118   -1.1259   
1963-10-31   -0.4100   -0.7756    3.0082    1.3636  ...    2.5648    3.1094   
1963-11-30   -1.2949   -1.5247    2.4487   -1.1674  ...   -0.1557   -3.2738   
...              ...       ...       ...       ...  ...       ...       ...   
2025-06-30    5.0853    3.4195    3.9194    8.9091  ...    4.4698    4.0870   
2025-07-31    2.5597    2.8325   -0.3417    0.7527  ...   -0.5678    0.6860   
2025-08-31    2.6550   -3.1379    6.0009   -1.0118  ...    5.0946    5.8753   
2025-09-30   -1.3741   -1.2434    3.2207    0.5132  ...    0.2006   -2.0899   
2025-10-31   -0.6184    9.3648   -1.4429   -1.2558  ...   -2.1622   -1.9337   

            BM4 INV3  BM4 INV4  BM4 INV5  HiBM LoINV  BM5 INV2  BM5 INV3  \
Date                                                                       
1963-07-31   -1.6069   -1.4316    0.1411     -1.7054    0.3671   -1.8900   
1963-08-31    4.6837   10.2504    4.7698      6.8141    4.6426    5.2209   
1963-09-30   -0.2319    2.3093   -3.4333     -1.7073   -3.6667   -1.4079   
1963-10-31    3.3142    6.7305   -2.6832      1.9789    2.7136   -2.1706   
1963-11-30   -1.9294   -2.7054   -1.8699     -1.3569   -2.4269   -0.5797   
...              ...       ...       ...         ...       ...       ...   
2025-06-30    4.1369    5.7323    1.9741      6.3811    6.4907    5.5411   
2025-07-31    0.6841   -1.2547    0.2360     -0.2527    1.0862   -3.9192   
2025-08-31    5.6667    4.8536    3.8672      5.8249    6.2606   13.1171   
2025-09-30    0.6538   -0.2927    0.7839      8.0290    0.7580    9.7441   
2025-10-31   -1.6378   -4.0054   -2.3911      3.2528   -2.3849    7.7300   

            BM5 INV4  HiBM HiINV  
Date                              
1963-07-31   -2.1494      3.5678  
1963-08-31    4.7120      8.7846  
1963-09-30   -4.4496      1.9201  
1963-10-31   -3.0794      4.2533  
1963-11-30    3.9112     -1.9139  
...              ...         ...  
2025-06-30    6.1110      7.0071  
2025-07-31   -2.3410      4.0391  
2025-08-31   11.7975      8.2898  
2025-09-30   -0.9914      2.6492  
2025-10-31   -4.8914     -1.3422  

[748 rows x 25 columns]

In [5]:
# DIMENSIONS
T = df_excess_rets.shape[0]
N_port = df_excess_rets.shape[1]

In [6]:
# ==============================================================================
# 1. TIME SERIES AVERAGE RETURNS, VOLATILITIES, & SHARPE RATIOS
# ==============================================================================
average_returns_ex_5X5 = np.zeros((5, 5))
volatility_returns_ex_5X5 = np.zeros((5, 5))

for i in range(5):
    average_returns_ex_5X5[i, :] = df_excess_rets.iloc[:, 5*i:5*(i+1)].mean(axis=0)
    volatility_returns_ex_5X5[i, :] = df_excess_rets.iloc[:, 5*i:5*(i+1)].std(axis=0)

sharpe_ratios_ex_5X5 = average_returns_ex_5X5 / volatility_returns_ex_5X5

print("Avg Excess Returns")
display(average_returns_ex_5X5)

print("Excess Return Volatilities")
display(volatility_returns_ex_5X5)

print("Sharpe Ratios")
display(sharpe_ratios_ex_5X5)

Avg Excess Returns


array([[0.61088382, 0.62807634, 0.63828797, 0.64176604, 0.67283289],
       [0.74263663, 0.71378529, 0.4822373 , 0.57945134, 0.60636484],
       [0.7759857 , 0.68041698, 0.69015521, 0.64827112, 0.46899973],
       [0.7632123 , 0.65179144, 0.78096243, 0.77502968, 0.61895428],
       [1.02545775, 0.88745575, 0.82890896, 0.94322821, 0.60935842]])

Excess Return Volatilities


array([[5.47523874, 4.64831288, 4.59897633, 4.81857195, 6.17309765],
       [5.06581059, 4.5167948 , 4.61516966, 4.84902616, 5.56584598],
       [5.20645958, 4.49112682, 4.49523544, 4.74603319, 5.64490025],
       [5.40461008, 4.61543906, 4.76629599, 5.53728377, 5.55589799],
       [6.05303993, 5.46423033, 5.69402357, 6.19705853, 6.65628475]])

Sharpe Ratios


array([[0.11157209, 0.1351192 , 0.13878914, 0.13318594, 0.10899437],
       [0.14659779, 0.15802916, 0.10448961, 0.1194985 , 0.10894388],
       [0.14904287, 0.15150251, 0.15353038, 0.1365922 , 0.08308379],
       [0.14121505, 0.14121981, 0.16385101, 0.13996568, 0.1114049 ],
       [0.16941203, 0.16241185, 0.14557526, 0.15220579, 0.09154633]])

In [7]:
# ==============================================================================
# 2. GENERATE PREMIUMS: MEAN OF TIME SERIES DIFFERENCES (LONG-SHORT PORTFOLIOS)
# ==============================================================================
X_const = np.ones((T, 1))

# initialize variables
value_premium = np.zeros(5)
value_premium_tstat = np.zeros(5)
value_premium_r2 = np.zeros(5)

inv_premium = np.zeros(5)
inv_premium_tstat = np.zeros(5)
inv_premium_r2 = np.zeros(5)

for i in range(5):
    # VALUE PREMIUM (High Value - Low Value) within each Investment quintile
    
    # high_value_idx = 5*4 + i; V5, I=i (so this would be 20th portfolio...)
    # low_value_idx  = 5*0 + i; V1, I=i (and this would be 1st portfolio...continuing in the loop for each quintile)
    
    Y = df_excess_rets.iloc[:, 5*4 + i] - df_excess_rets.iloc[:, 5*0 + i]
    
    model = sm.OLS(Y, X_const).fit(
        cov_type="HAC",
        cov_kwds={"maxlags": 6}
    )
    
    value_premium[i] = model.params.iloc[0]
    value_premium_tstat[i] = model.tvalues.iloc[0]
    value_premium_r2[i] = model.rsquared_adj

    # INVESTMENT PREMIUM (High Inv - Low Inv) within each Value quintile
    Y = df_excess_rets.iloc[:, 5*i + 4] - df_excess_rets.iloc[:, 5*i + 0] # flipped
    
    model = sm.OLS(Y, X_const).fit(
        cov_type="HAC",
        cov_kwds={"maxlags": 6}
    )
    
    inv_premium[i] = model.params.iloc[0]
    inv_premium_tstat[i] = model.tvalues.iloc[0]
    inv_premium_r2[i] = model.rsquared_adj

In [8]:
# Report mean of monthly long-short returns
# Value Premium
investment_labels = [
    "Low Inv",
    "Inv 2",
    "Inv 3",
    "Inv 4",
    "High Inv"
]

value_premium_table = pd.DataFrame({
    "Value 5–1": value_premium,
    "t-stat": value_premium_tstat
}, index=investment_labels)

display(value_premium_table)

# Investment Premium
value_labels = [
    "Low Value",
    "Value 2",
    "Value 3",
    "Value 4",
    "High Value"
]

inv_premium_table = pd.DataFrame({
    "Inv 5–1": inv_premium,
    "t-stat": inv_premium_tstat
}, index=value_labels)

display(inv_premium_table)


Value 5–1    t-stat
Low Inv    0.414574  2.262640
Inv 2      0.259379  1.593394
Inv 3      0.190621  1.096354
Inv 4      0.301462  1.618911
High Inv  -0.063474 -0.296303

Inv 5–1    t-stat
Low Value   0.061949  0.387730
Value 2    -0.136272 -1.064414
Value 3    -0.306986 -2.224709
Value 4    -0.144258 -1.168384
High Value -0.416099 -3.080793

In [9]:
# define the Newey-West Test for mean significance
def nw_mean_test(y, lags=6): # fix lags at 6 matching EAP BEM
    """
    Newey–West test of mean = 0
    """
    y = y.values
    X = np.ones(len(y))
    model = sm.OLS(y, X).fit(
        cov_type="HAC",
        cov_kwds={"maxlags": lags}
    )
    return model.params[0], model.tvalues[0]


In [10]:
# compute investment premium
HL_INV_mean = np.zeros(5)
HL_INV_tstat = np.zeros(5)

for i in range(5):  # value quintiles
    high = df_excess_rets.iloc[:, 5*i + 4]
    low  = df_excess_rets.iloc[:, 5*i]
    spread = high - low

    HL_INV_mean[i], HL_INV_tstat[i] = nw_mean_test(spread)

# compute value premium (within investment quintiles)
HL_VALUE_mean = np.zeros(5)
HL_VALUE_tstat = np.zeros(5)

for i in range(5):  # investment quintiles
    high = df_excess_rets.iloc[:, i + 20]
    low  = df_excess_rets.iloc[:, i]
    spread = high - low

    HL_VALUE_mean[i], HL_VALUE_tstat[i] = nw_mean_test(spread)

# display results
df_HL_INV = pd.DataFrame({
    "Mean": HL_INV_mean,
    "NW t-stat": HL_INV_tstat
}, index=["Low Value","2","3","4","High Value"])

df_HL_VALUE = pd.DataFrame({
    "Mean": HL_VALUE_mean,
    "NW t-stat": HL_VALUE_tstat
}, index=["Low Inv","2","3","4","High Inv"])

display(df_HL_INV)
display(df_HL_VALUE)


Mean  NW t-stat
Low Value   0.061949   0.387730
2          -0.136272  -1.064414
3          -0.306986  -2.224709
4          -0.144258  -1.168384
High Value -0.416099  -3.080793

Mean  NW t-stat
Low Inv   0.414574   2.262640
2         0.259379   1.593394
3         0.190621   1.096354
4         0.301462   1.618911
High Inv -0.063474  -0.296303

---

## CAPM Analysis

#### For each portfolio, estimate:
$R_{j,t} - R_{f,t} = \alpha_j + \beta_j R_{Mkt-RF,t} + \epsilon_{j,t}$, 

$ where j = 1,..., 25$

In [11]:
# ==============================================================================
# 3. CAPM ANALYSIS
# ==============================================================================

# T x 1 market excess return
mkt = df_raw['Mkt-RF'].values.reshape(-1, 1)

X = np.column_stack(                # T x 2 regressor matrix
    [np.ones(T), 
     mkt
     ])

# initialize variables
coeff = np.zeros((2, N_port))
tstat_nw = np.zeros((2, N_port))
r2_adj = np.zeros(N_port)
alpha_CAPM = np.zeros(N_port)
tstat_alpha_CAPM = np.zeros(N_port)
beta_CAPM = np.zeros(N_port)
tstat_beta_CAPM = np.zeros(N_port)
error = np.zeros((T, N_port))

for j in range(N_port):

    # excess returns
    Y = df_excess_rets.iloc[:, j]

    # OLS regression
    model = sm.OLS(Y, X).fit(
        cov_type="HAC",
        cov_kwds={"maxlags": 6}
    )

    coeff[:, j] = model.params
    tstat_nw[:, j] = model.tvalues
    r2_adj[j] = model.rsquared_adj
    alpha_CAPM[j] = coeff[0, j]
    tstat_alpha_CAPM[j] = tstat_nw[0, j]
    error[:, j] = Y - X @ coeff[:, j]
    beta_CAPM[j] = coeff[1, j]
    tstat_beta_CAPM[j] = tstat_nw[1, j]

print(alpha_CAPM.shape)
print(beta_CAPM.shape)
print(error.shape)  
print(np.mean(error, axis=0))

(25,)
(25,)
(748, 25)
[ 1.67424007e-16  2.51136010e-16  1.15771920e-16  3.79969377e-17
  2.86758140e-16  2.77852607e-16 -9.85545573e-17  5.93702152e-18
  2.63603756e-16  1.58518475e-16  1.73361028e-16 -6.11513217e-17
 -8.96490250e-17  1.11912856e-16  1.33582984e-16  2.73102990e-17
 -5.34331937e-17  1.32395580e-16  3.95405633e-16 -4.74961722e-18
 -9.49923444e-17  2.61228947e-17  1.69798816e-16  2.73102990e-17
  2.74290394e-16]


In [12]:
# form 5x5 tables for CAPM variables

# initialize
beta_CAPM_5X5   = np.zeros((5, 5))
r2_CAPM_5X5     = np.zeros((5, 5))
alpha_CAPM_5X5  = np.zeros((5, 5))
tstat_CAPM_5X5  = np.zeros((5, 5))

# loop through and collect terms
for i in range(5):
    start = 5 * i
    end = 5 * (i + 1)
    
    beta_CAPM_5X5[i,:]   = beta_CAPM[start:end]
    r2_CAPM_5X5[i,:]     = r2_adj[start:end]
    alpha_CAPM_5X5[i,:]  = alpha_CAPM[start:end]
    tstat_CAPM_5X5[i,:]  = tstat_alpha_CAPM[start:end]

print("beta_CAPM_5X5")
display(beta_CAPM_5X5)
print("r2_CAPM_5X5")
display(r2_CAPM_5X5)
print("alpha_CAPM_5X5")
display(alpha_CAPM_5X5)
print("tstat_CAPM_5X5")
display(tstat_CAPM_5X5)

beta_CAPM_5X5


array([[1.07186876, 0.90525316, 0.92874369, 0.98031158, 1.24654101],
       [0.96012242, 0.88103023, 0.93552108, 0.99777759, 1.13389379],
       [1.00703966, 0.85675236, 0.86659364, 0.92769003, 1.11462003],
       [1.00912594, 0.85118661, 0.89074853, 1.01896726, 1.03918372],
       [1.07842   , 0.99050909, 0.98595969, 1.09205642, 1.22528597]])

r2_CAPM_5X5


array([[0.76364576, 0.75571186, 0.81269985, 0.82482699, 0.81258261],
       [0.71568046, 0.75810642, 0.81883792, 0.84381178, 0.8270954 ],
       [0.74542574, 0.72506064, 0.7404865 , 0.76130159, 0.77690689],
       [0.6945462 , 0.67755051, 0.6958071 , 0.67459216, 0.69697659],
       [0.63224514, 0.65455623, 0.59714872, 0.61852218, 0.67503469]])

alpha_CAPM_5X5


array([[-0.02849736,  0.08808315,  0.08428242,  0.0569997 , -0.07074216],
       [ 0.16991334,  0.18824134, -0.07581103, -0.01573367, -0.07001493],
       [ 0.17527577,  0.16935503,  0.17322284,  0.0948941 , -0.19588304],
       [ 0.16125788,  0.14404953,  0.24962141,  0.16720481, -0.00092992],
       [ 0.38216869,  0.29660649,  0.24077346,  0.29180487, -0.12153776]])

tstat_CAPM_5X5


array([[-0.2569596 ,  1.08483959,  1.16394922,  0.69956715, -0.62868004],
       [ 1.54613654,  1.94752091, -1.00334439, -0.20262861, -0.76647289],
       [ 1.53142749,  1.84338492,  1.79421196,  0.96561696, -1.86772335],
       [ 1.24076095,  1.21113045,  1.9993257 ,  1.12416376, -0.00782078],
       [ 2.21016313,  2.15999969,  1.55654553,  1.99633684, -0.75996863]])

In [13]:
# Gibbons-Ross-Shanken Test for joint significance of alphas
K = X.shape[1] - 1  # number of factors (CAPM has one, Mkt Beta)

# covariance matrices
cov_e = np.cov(error, rowvar=False)
cov_f = np.atleast_2d(np.cov(X[:,1:], rowvar=False))

# mean of factor returns
e_f = X[:,1:].mean(axis=0).reshape(K,1)

# reshape alpha to column vector
alpha = alpha_CAPM.reshape(N_port,1)

# GRS
inv_term = 1 + (e_f.T @ np.linalg.inv(cov_f) @ e_f)
grs_num = (T - N_port - K) / N_port * (alpha.T @ np.linalg.inv(cov_e) @ alpha) / inv_term
grs_value_CAPM = grs_num.item()  # scalar

p_value_CAPM = 1 - f.cdf(grs_value_CAPM, N_port, T - N_port - K)

print("GRS F-statistic:", grs_value_CAPM)
print("p-value:", p_value_CAPM)

GRS F-statistic: 2.1385281689909346
p-value: 0.0010695311859535428


---

## FF5 Analysis

#### For each portfolio, estimate:
$R_{j,t} - R_{f,t} = \alpha_j + \beta_{j,Mkt} R_{Mkt-RF,t} + \beta_{j,SMB} R_{SMB,t} + \beta_{j,HML} R_{HML,t} + \beta_{j,RMW} R_{RMW,t} + \beta_{j,CMA} R_{CMA,t} + \epsilon_{j,t}$, 

$ where j = 1,..., 25$

In [14]:
# ==============================================================================
# 4. FAMA-FRENCH 5-FACTOR ANALYSIS
# ==============================================================================

# T x 1 for each of the FF5 Factors
mkt = df_raw['Mkt-RF'].values.reshape(-1, 1)    # market excess return (ER)
SMB = df_raw['SMB'].values.reshape(-1, 1)       # size ER
HML = df_raw['HML'].values.reshape(-1, 1)       # value ER
RMW = df_raw['RMW'].values.reshape(-1, 1)       # operating profitability ER
CMA = df_raw['CMA'].values.reshape(-1, 1)       # investment ER

X = np.column_stack(                # T x 6 regressor matrix
    [np.ones(T), 
     mkt,
     SMB,
     HML,
     RMW,
     CMA
     ])

# initialize variables
coeff = np.zeros((6, N_port))
tstat_nw = np.zeros((6, N_port))
r2_adj = np.zeros(N_port)
alpha_FF5 = np.zeros(N_port)
tstat_alpha_FF5 = np.zeros(N_port)
beta_FF5 = np.zeros((5, N_port))
tstat_beta_FF5 = np.zeros((5, N_port))
error = np.zeros((T, N_port))

for j in range(N_port):

    # excess returns
    Y = df_excess_rets.iloc[:, j]

    # OLS regression
    model = sm.OLS(Y, X).fit(
        cov_type="HAC",
        cov_kwds={"maxlags": 6}
    )

    coeff[:, j] = model.params
    tstat_nw[:, j] = model.tvalues
    r2_adj[j] = model.rsquared_adj
    alpha_FF5[j] = coeff[0, j]
    tstat_alpha_FF5[j] = tstat_nw[0, j]
    error[:, j] = Y - X @ coeff[:, j]
    beta_FF5[:, j] = coeff[1:, j]
    tstat_beta_FF5[:, j] = tstat_nw[1:, j]

print(alpha_FF5.shape)
print(beta_FF5.shape)
print(error.shape)  
print(np.mean(error, axis=0))

(25,)
(5, 25)
(748, 25)
[-9.24987953e-16  3.39300780e-16  3.11693630e-16  9.13113910e-16
  1.86095940e-15 -1.36373384e-15 -1.45249232e-15 -1.00929366e-15
 -7.72406500e-16 -6.29917983e-16 -2.49785338e-15 -1.79713641e-15
 -1.71223701e-15 -1.96515412e-15 -1.42592414e-15 -3.53401206e-15
 -3.05459757e-15 -2.65384862e-15 -3.32354465e-15 -2.56835551e-15
 -4.20222383e-15 -4.01698876e-15 -3.93387046e-15 -4.19272460e-15
 -3.52243487e-15]


In [15]:
# form 5x5 tables for FF5 variables

# initialize
beta_MKT_FF5_5X5    = np.zeros((5, 5))
beta_SMB_FF5_5X5    = np.zeros((5, 5))
beta_HML_FF5_5X5    = np.zeros((5, 5))
beta_RMW_FF5_5X5    = np.zeros((5, 5))
beta_CMA_FF5_5X5    = np.zeros((5, 5))
r2_FF5_5X5          = np.zeros((5, 5))
alpha_FF5_5X5       = np.zeros((5, 5))
tstat_FF5_5X5       = np.zeros((5, 5))

# loop through and collect terms
for i in range(5):
    start = 5 * i
    end = 5 * (i + 1)
    
    beta_MKT_FF5_5X5[i, :]  = beta_FF5[0, start:end]
    beta_SMB_FF5_5X5[i, :]  = beta_FF5[1, start:end]
    beta_HML_FF5_5X5[i, :]  = beta_FF5[2, start:end]
    beta_RMW_FF5_5X5[i, :]  = beta_FF5[3, start:end]
    beta_CMA_FF5_5X5[i, :]  = beta_FF5[4, start:end]
    r2_FF5_5X5[i,:]         = r2_adj[start:end]
    alpha_FF5_5X5[i,:]     = alpha_FF5[start:end]
    tstat_FF5_5X5[i,:]     = tstat_alpha_FF5[start:end]

print("beta_MKT_FF5_5X5")
display(beta_MKT_FF5_5X5)
print("beta_SMB_FF5_5X5")
display(beta_SMB_FF5_5X5)
print("beta_HML_FF5_5X5")
display(beta_HML_FF5_5X5)
print("beta_RMW_FF5_5X5")
display(beta_RMW_FF5_5X5)
print("beta_CMA_FF5_5X5")
display(beta_CMA_FF5_5X5)

print("alpha_FF5_5X5")
display(alpha_FF5_5X5)
print("tstat_FF5_5X5")
display(tstat_FF5_5X5)
print("r2_FF5_5X5")
display(r2_FF5_5X5)

beta_MKT_FF5_5X5


array([[1.13807124, 0.97866016, 0.97306244, 0.97030482, 1.0734414 ],
       [1.04060139, 0.96491762, 0.97254067, 1.01260443, 1.08553809],
       [1.06962485, 0.95506617, 0.96049296, 0.96705294, 1.07511436],
       [1.09584652, 0.96966707, 0.95586162, 1.05196717, 1.0237315 ],
       [1.11791262, 1.05353764, 0.99415447, 1.10171153, 1.17368606]])

beta_SMB_FF5_5X5


array([[ 0.1488096 , -0.11240267, -0.08701496, -0.10788684,  0.06781705],
       [ 0.1704658 ,  0.03949179,  0.02419672,  0.07285027,  0.15404344],
       [ 0.22280078,  0.00159379, -0.02170156,  0.08094748,  0.16429041],
       [ 0.26859812,  0.06683144,  0.12122162,  0.1660451 ,  0.20417238],
       [ 0.46523909,  0.21494458,  0.32442695,  0.32644039,  0.49016273]])

beta_HML_FF5_5X5


array([[-0.47534141, -0.32776755, -0.18797421, -0.26171296, -0.37752101],
       [-0.1544712 , -0.07549236,  0.03281998,  0.07998086,  0.14845064],
       [ 0.18759944,  0.10550957,  0.30170032,  0.43578009,  0.43506122],
       [ 0.40791945,  0.47713982,  0.53356677,  0.76290927,  0.74631856],
       [ 0.55966309,  0.80839918,  0.93581176,  0.9945691 ,  0.70382597]])

beta_RMW_FF5_5X5


array([[ 0.15374759,  0.25169022,  0.3276002 ,  0.23490892, -0.04593186],
       [ 0.19214683,  0.17393038,  0.11355447,  0.27038353,  0.12895207],
       [ 0.04675296,  0.0902505 ,  0.20646321,  0.14574568,  0.04254162],
       [ 0.07293092,  0.10273595,  0.07887769, -0.06760046,  0.00485225],
       [-0.11997741, -0.05736528, -0.0753467 , -0.0508497 , -0.09903742]])

beta_CMA_FF5_5X5


array([[ 0.88751927,  0.45119632,  0.14058034, -0.10050332, -0.63823553],
       [ 0.7075138 ,  0.52220257,  0.16127322, -0.04920348, -0.31901172],
       [ 0.45400495,  0.4630987 ,  0.17701884, -0.1170923 , -0.44437371],
       [ 0.45379017,  0.34141187,  0.04317248, -0.21053599, -0.49151546],
       [ 0.37379096, -0.0147059 , -0.3218867 , -0.3742511 , -0.28909024]])

alpha_FF5_5X5


array([[-0.21521562, -0.01830475,  0.00647859,  0.11801272,  0.29102957],
       [-0.08551602, -0.01862811, -0.17976336, -0.11870731, -0.06714644],
       [-0.07539871, -0.05380837, -0.0595463 , -0.0745734 , -0.2274131 ],
       [-0.18024574, -0.18051349,  0.00930221, -0.02675231, -0.11960454],
       [ 0.06102046,  0.01361569,  0.01387773,  0.05346062, -0.27929216]])

tstat_FF5_5X5


array([[-2.16169517, -0.25808508,  0.10835705,  1.72128431,  4.47929928],
       [-0.83824923, -0.26472729, -2.41872043, -1.74724735, -0.7191421 ],
       [-0.87624579, -0.72121805, -0.8667522 , -1.08494877, -2.03015133],
       [-2.10908673, -2.64293264,  0.11313538, -0.25514523, -1.24919238],
       [ 0.63665093,  0.18069792,  0.14314619,  0.55691481, -2.64166411]])

r2_FF5_5X5


array([[0.82009592, 0.80085303, 0.85037206, 0.87956718, 0.93169275],
       [0.77067619, 0.798337  , 0.82708595, 0.85918226, 0.84143994],
       [0.82425903, 0.7875651 , 0.81495166, 0.82611074, 0.81355632],
       [0.84039361, 0.85049026, 0.81864243, 0.81366497, 0.80580268],
       [0.82785823, 0.85744398, 0.80741668, 0.81070746, 0.80015387]])

In [16]:
# Gibbons-Ross-Shanken Test for joint significance of alphas
K = X.shape[1] - 1  # 5 for FF5

# covariance matrices
cov_e = np.cov(error, rowvar=False)
cov_f = np.atleast_2d(np.cov(X[:, 1:], rowvar=False))

# mean of factor returns
e_f = X[:, 1:].mean(axis=0).reshape(K,1)

# reshape FF5 alphas to column vector
alpha = alpha_FF5.reshape(N_port,1)

# GRS statistic
inv_term = 1 + (e_f.T @ np.linalg.inv(cov_f) @ e_f)
grs_num = (T - N_port - K) / N_port * (alpha.T @ np.linalg.inv(cov_e) @ alpha) / inv_term
grs_value_FF5 = grs_num.item()  # scalar

# p-value
p_value_FF5 = 1 - f.cdf(grs_value_FF5, N_port, T - N_port - K)

print("GRS F-statistic (FF5):", grs_value_FF5)
print("p-value (FF5):", p_value_FF5)

GRS F-statistic (FF5): 2.381371091789847
p-value (FF5): 0.00018995773655405834


In [17]:
# ==============================================================================
# 5. ALPHA COMPARISON: CAPM VS. FF5
# ==============================================================================

print("CAPM Average Pricing Error:") # mean of absolute value of all 25 alphas
display(f"{np.mean(abs(alpha_CAPM_5X5))}")

print("FF5 Average Pricing Error:") # mean of absolute value of all 25 alphas
display(f"{np.mean(abs(alpha_FF5_5X5))}")

CAPM Average Pricing Error:


'0.14851618750000375'

FF5 Average Pricing Error:


'0.10188909314905775'

In [18]:
# Average Market Beta Comparison

beta_mkt_FF5 = beta_FF5[0, :]

avg_beta_CAPM = np.mean(beta_CAPM)
avg_beta_FF5 = np.mean(beta_mkt_FF5)

print("Average market beta (CAPM):", avg_beta_CAPM)
print("Average market beta (FF5):", avg_beta_FF5)

Average market beta (CAPM): 0.9998080900527272
Average market beta (FF5): 1.0310067888065533
